gpgme: Fix build for Linux
- Error:
  ```
  creating python2.7-gpg/temp.linux-x86_64-2.7/python2.7-gpg
  gcc-5 -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -Wall -Wcast-align -Wshadow -Wstrict-prototypes -fPIC -DHAVE_DATA_H=1 -DIN_TREE_BUILD=1 -DHAVE_CONFIG_H=1 -Ipython2.7-gpg -I/tmp/gpgme-20190714-6575-c17216/gpgme-1.13.0/lang/python -I/home/linuxbrew/.linuxbrew/Cellar/gpgme/1.13.0_1/include -I/home/linuxbrew/.linuxbrew/opt/libassuan/include -I/home/linuxbrew/.linuxbrew/opt/libgpg-error/include -I/usr/include/python2.7 -c python2.7-gpg/gpgme_wrap.c -o python2.7-gpg/temp.linux-x86_64-2.7/python2.7-gpg/gpgme_wrap.o
  python2.7-gpg/gpgme_wrap.c:155:21: fatal error: Python.h: No such file or directory
  ```
- The build and tests require Python 2 as well as Python 3.